[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@semaphore-protocol/=lib/semaphore/packages/contracts/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "solmate/=lib/solmate/src/",
    "solady/=lib/solady/src/"
]

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000
depth = 500